version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 &
             celery -A whatsapp_integration worker --loglevel=info"
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  redis:
    image: redis:6
    ports:
      - "6379:6379"